name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: wpilib/roborio-cross-ubuntu:2023-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Grant execute permission # just in case
        run: chmod +x gradlew
      - name: Compile robot code
        run: ./gradlew build
  # test:
  #   needs: build
  #   steps:
  #     - name: Simulate robot code
  #     run: ./gradlew test
